---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: ubuntu-2204
    image: saikolab/ubuntu-2204
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
