name: Ansible Lint # feel free to pick your own name
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted #ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        # optional:
        # with:
        #   path: "playbooks/"  # <-- only one value is allowed
